apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        image: srinisdockerepo/nodejs:61
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
