apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: srinisdockerepo/nodejs:11
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
